KusionStack/charts

- .github/configs/ct-lint.yaml
- charts/operating
- versions/operating/0.3.0/Chart.yaml
- versions/operating/0.3.0/templates/NOTES.txt
- versions/operating/0.3.0/templates/crd/apps.kusionstack.io_collasets.yaml
- versions/operating/0.3.0/templates/crd/apps.kusionstack.io_poddecorations.yaml
- versions/operating/0.3.0/templates/crd/apps.kusionstack.io_podtransitionrules.yaml
- versions/operating/0.3.0/templates/crd/apps.kusionstack.io_resourcecontexts.yaml
- versions/operating/0.3.0/templates/namespace.yaml
- versions/operating/0.3.0/templates/rbac/rbac.yaml
- versions/operating/0.3.0/templates/service.yaml
- versions/operating/0.3.0/templates/shardingconfig.yaml
- versions/operating/0.3.0/templates/statefulset.yaml
- versions/operating/0.3.0/templates/webhook/webhook.yaml
- versions/operating/0.3.0/values.yaml
> release operating 0.3.0 chart

- charts/operating
- versions/operating/0.4.0/Chart.yaml
- versions/operating/0.4.0/templates/NOTES.txt
- versions/operating/0.4.0/templates/crd/apps.kusionstack.io_collasets.yaml
- versions/operating/0.4.0/templates/crd/apps.kusionstack.io_poddecorations.yaml
- versions/operating/0.4.0/templates/crd/apps.kusionstack.io_podtransitionrules.yaml
- versions/operating/0.4.0/templates/crd/apps.kusionstack.io_resourcecontexts.yaml
- versions/operating/0.4.0/templates/namespace.yaml
- versions/operating/0.4.0/templates/rbac/rbac.yaml
- versions/operating/0.4.0/templates/service.yaml
- versions/operating/0.4.0/templates/shardingconfig.yaml
- versions/operating/0.4.0/templates/statefulset.yaml
- versions/operating/0.4.0/templates/webhook/webhook.yaml
- versions/operating/0.4.0/values.yaml
> feat: add operating 0.4.0 helm chart

- versions/karpor/0.4.1/.helmignore
- versions/karpor/0.4.1/Chart.yaml
- versions/karpor/0.4.1/templates/elasticsearch.yml
- versions/karpor/0.4.1/templates/etcd.yml
- versions/karpor/0.4.1/templates/job.yml
- versions/karpor/0.4.1/templates/karpor-server.yml
- versions/karpor/0.4.1/templates/karpor-sync.yml
- versions/karpor/0.4.1/templates/namespace.yml
- versions/karpor/0.4.1/values.yaml
> feat: add new version v0.4.1 as unstable version for karpor

- charts/karpor
> refactor: bump karpor version to v0.4.1

- index.yaml
> chore: remove unused karpor version 0.3.14-alpha.5 in index.yaml

- charts/karpor/Chart.yaml
- charts/karpor/README.md
- charts/karpor/templates/_common.tpl
- charts/karpor/templates/elasticsearch.yml
- charts/karpor/templates/etcd.yml
- charts/karpor/templates/job.yml
- charts/karpor/templates/karpor-server.yml
- charts/karpor/templates/karpor-syncer.yml
- charts/karpor/values.yaml
> feat: support specify registry proxy in karpor chart

- charts/karpor/Chart.yaml
- charts/karpor/README.md
> refactor: bump karpor app version to v0.4.5

- charts/karpor/Chart.yaml
- charts/karpor/README.md
> refactor: bump karpor version to v0.4.6

- charts/karpor/Chart.yaml
- charts/karpor/README.md
> refactor: bump karpor image version to v0.4.8

- charts/karpor/Chart.yaml
- charts/karpor/README.md
> refactor: bump karpor version to v0.4.10

- OWNERS
> chore: add more users to owners

- README.md
- charts/karpor/Chart.yaml
- charts/karpor/README.md
- charts/karpor/README.md.gotmpl
> docs: add badges

- charts/karpor/Chart.yaml
> refactor: bump karpor version to v0.4.11

- charts/karpor/Chart.yaml
- charts/karpor/README.md
> refactor: bump karpor app version to v0.5.0

- charts/karpor/Chart.yaml
- charts/karpor/README.md
> refactor: bump karpor app version to v0.5.1

- charts/karpor/Chart.yaml
- charts/karpor/README.md
> refactor: bump karpor app version to v0.5.2

- charts/kuperator
- versions/kuperator/0.6.0/Chart.yaml
- versions/kuperator/0.6.0/templates/NOTES.txt
- versions/kuperator/0.6.0/templates/crd/apps.kusionstack.io_collasets.yaml
- versions/kuperator/0.6.0/templates/crd/apps.kusionstack.io_operationjobs.yaml
- versions/kuperator/0.6.0/templates/crd/apps.kusionstack.io_poddecorations.yaml
- versions/kuperator/0.6.0/templates/crd/apps.kusionstack.io_podtransitionrules.yaml
- versions/kuperator/0.6.0/templates/crd/apps.kusionstack.io_resourcecontexts.yaml
- versions/kuperator/0.6.0/templates/namespace.yaml
- versions/kuperator/0.6.0/templates/rbac/rbac.yaml
- versions/kuperator/0.6.0/templates/service.yaml
- versions/kuperator/0.6.0/templates/shardingconfig.yaml
- versions/kuperator/0.6.0/templates/statefulset.yaml
- versions/kuperator/0.6.0/templates/webhook/webhook.yaml
- versions/kuperator/0.6.0/values.yaml
> feat: update kuperator charts to 0.6.0

- charts/karpor/Chart.yaml
- charts/karpor/README.md
- charts/karpor/templates/karpor-server.yml
- charts/karpor/values.yaml
- feat: https://github.com/KusionStack/karpor/issues/548
- charts/karpor/
- feat: add service type for karpor server
- N
```release-note
None
```
> feat: add service type for karpor server

- charts/karpor/Chart.yaml
- charts/karpor/README.md
> chore(karpor): bump chart version to 0.6.15

- charts/karpor/Chart.yaml
- charts/karpor/README.md
> chore(karpor): bump version to v0.5.8

- charts/karpor/Chart.yaml
- charts/karpor/README.md
> docs(karpor): remove version badge in readme

- charts/karpor/Chart.yaml
- charts/karpor/README.md
- charts/karpor/templates/karpor-server.yml
- charts/karpor/values.yaml
> chore: add server.enableRbac to values.yaml of karpor

- charts/karpor/Chart.yaml
- charts/karpor/README.md
- charts/karpor/templates/karpor-server.yml
- charts/karpor/values.yaml
> feat(karpor): add AI parameters to Karpor's values

- charts/kusion/Chart.yaml
- charts/kusion/README.md
- charts/kusion/README.md.gotmpl
charts/kusion/README.md
charts/kusion/README.md.gotmpl
Update `kusion server` installation instruction in README template and README
```release-note
None
```
> docs: update kusion installation instruction

- charts/karpor/Chart.yaml
- charts/karpor/templates/karpor-server.yml
fix typo : secret label bug
charts/charts/karpor/templates/karpor-server.yml:19
bug fix
```yaml
apiVersion: v1
kind: Secret
metadata:
name: karpor-auth
namespace: {{ .Values.namespace }}
labesl: {{- include "karpor.labels" (dict "context" . "component" .Values.server.name) | nindent 4 }}
```
The label field is wrong, and the label of the Secret control through Values.yaml ​​will not take effect!
```release-note
None
```
> fix secret labels typo "labesl"

- charts/karpor/Chart.yaml
- charts/karpor/README.md
- charts/karpor/values.yaml
- Increment version in Chart.yaml from 0.7.1 to 0.7.2
- Update README.md and values.yaml to include detailed AI backend options
This commit updates the project version and improves documentation clarity by listing available AI backend options, including OpenAI, Azure OpenAI, and Hugging Face.
```release-note
None
```
> chore: bump version to 0.7.2 and update AI backend docs

- charts/kuperator
- versions/kuperator/0.6.2/Chart.yaml
- versions/kuperator/0.6.2/templates/NOTES.txt
- versions/kuperator/0.6.2/templates/crd/apps.kusionstack.io_collasets.yaml
- versions/kuperator/0.6.2/templates/crd/apps.kusionstack.io_operationjobs.yaml
- versions/kuperator/0.6.2/templates/crd/apps.kusionstack.io_poddecorations.yaml
- versions/kuperator/0.6.2/templates/crd/apps.kusionstack.io_podtransitionrules.yaml
- versions/kuperator/0.6.2/templates/crd/apps.kusionstack.io_resourcecontexts.yaml
- versions/kuperator/0.6.2/templates/namespace.yaml
- versions/kuperator/0.6.2/templates/rbac/rbac.yaml
- versions/kuperator/0.6.2/templates/service.yaml
- versions/kuperator/0.6.2/templates/shardingconfig.yaml
- versions/kuperator/0.6.2/templates/statefulset.yaml
- versions/kuperator/0.6.2/templates/webhook/webhook.yaml
- versions/kuperator/0.6.2/values.yaml
> chart: bump kuperator to v0.6.2

- scripts/install-kusion.sh
> fix: enhance usability of install-kusion.sh

- charts/kuperator
- versions/kuperator/0.6.3/Chart.yaml
- versions/kuperator/0.6.3/templates/NOTES.txt
- versions/kuperator/0.6.3/templates/crd/apps.kusionstack.io_collasets.yaml
- versions/kuperator/0.6.3/templates/crd/apps.kusionstack.io_operationjobs.yaml
- versions/kuperator/0.6.3/templates/crd/apps.kusionstack.io_poddecorations.yaml
- versions/kuperator/0.6.3/templates/crd/apps.kusionstack.io_podtransitionrules.yaml
- versions/kuperator/0.6.3/templates/crd/apps.kusionstack.io_resourcecontexts.yaml
- versions/kuperator/0.6.3/templates/namespace.yaml
- versions/kuperator/0.6.3/templates/rbac/rbac.yaml
- versions/kuperator/0.6.3/templates/service.yaml
- versions/kuperator/0.6.3/templates/shardingconfig.yaml
- versions/kuperator/0.6.3/templates/statefulset.yaml
- versions/kuperator/0.6.3/templates/webhook/webhook.yaml
- versions/kuperator/0.6.3/values.yaml
> bump Kuperator to v0.6.3
